apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec: 
  type: {{ .Values.spec.type }}
  version: {{ .Values.spec.version }}
  {{ if eq .Values.spec.type "policyproject" }}
  contents: {{ .Values.spec.contents }}
  {{ else }}
  secretName: {{ .Values.spec.contents }}
  {{ end }}
